# Generated by Django 5.2.13 on 2026-06-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        ('patients', '0002_patient_adresse_patient_groupe_sanguin_patient_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='patients.patient'),
        ),
    ]
