# Generated by Django 5.2.13 on 2026-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money (Airtel/MTN)'), ('carte', 'Carte Bancaire')], default='especes', max_length=20),
        ),
        migrations.AddField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente')], default='paye', max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
