# Generated by Django 5.2.13 on 2026-07-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0002_medecin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='numero_cabinet',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('orl_generale', 'ORL Générale'), ('audiologie', "Audiologie / Troubles de l'audition"), ('rhinologie', 'Rhinologie / Sinus et cloisons nasales'), ('laryngologie', 'Laryngologie / Voix et cordes vocales'), ('orl_pediatrique', 'ORL Pédiatrique')], default='orl_generale', max_length=50),
        ),
    ]
