# Generated by Django 5.2.13 on 2026-06-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0002_medecin_user'),
        ('patients', '0002_patient_adresse_patient_groupe_sanguin_patient_sexe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('motif', models.CharField(choices=[('consultation_generale', 'Consultation ORL Générale'), ('audiometrie', 'Bilan Auditif / Audiométrie'), ('sinusite', 'Troubles des Sinus / Nez bouché'), ('pharyngite', 'Maux de Gorge / Cordes Vocales'), ('vertiges', 'Gestion des Vertiges / Équilibre')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous', to='medecins.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rdv', 'heure_rdv'],
            },
        ),
    ]
