# Generated by Django 5.2.13 on 2026-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField()),
                ('date_visite', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('adresse_ip', 'date_visite')},
            },
        ),
    ]
